---
site:
  title: RHBPD Technical Lab 3
  url: https://github.com/rhpds/rhbpd-tl3
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui

asciidoc:
  attributes:
    showroom-collection-version: v1.5.2

antora:
  extensions:
    - '@andrew-jones/antora-tabs-extension'

output:
  dir: ./www
